spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customers
    username: mindgarden
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

  #data:
  #  mongodb:
  #    username: mindgarden
  #    password: password
  #    host: localhost
  #    port: 27017
  #    database: customers
  #    authentication-database: admin
server:
  port: 8090


